---
name: cross_platform_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - scipy
  - scikit-learn=1.5.0
  - boto3
  - botocore
  - cfgrib
  - pandas
  - netcdf4
  - numpy
  - joblib
  - jupyter
  - jupyterlab
  - ipykernel
  - matplotlib
  - pillow
  - zlib
  - zeromq
  - pyyaml
  - xarray
  - pip
  - pip:
      - absl-py
      - astunparse
      - flatbuffers
      - gast
      - google-pasta
      - grpcio
      - h5py
      - keras
      - libclang
      - markdown
      - markdown-it-py
      - mdurl
      - ml-dtypes
      - opt-einsum
      - optree
      - protobuf
      - rich
      - tensorboard
      - tensorboard-data-server
      - tensorflow
      - tensorflow-intel
      - termcolor
      - werkzeug
      - wrapt