---
name: Environment Setup
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
          - windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: cross_platform_env
          environment-file: requirements/environment.yml
          auto-update-conda: true
          miniconda-version: "latest"  # Specify to ensure Miniconda is downloaded and installed

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda env update -f requirements/environment.yml
          conda init bash
          conda config --set auto_activate_base false
          conda activate cross_platform_env

      - name: Check system architecture
        run: uname -m 

      - name: Verify environment activation
        shell: bash -l {0}
        run: |
          conda activate cross_platform_env
          echo $CONDA_DEFAULT_ENV
          conda list

      - name: Verify installation (import test)
        shell: bash -l {0}
        run: |
          conda activate cross_platform_env
          python tests/test_imports.py
