name: Build Sphinx Documentation

on:
  push:
    branches:
      - dcj-documentation-updates  # Include branches you want to build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Sphinx documentation
      run: |
        cd docs
        make html

    - name: Upload documentation
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: sphinx-docs
        path: docs/build/html